mode: auto

avatar:
  url: https://image.hananoryu.cn/images/hananoryu.png
  rounded: true
  opacity: 1

social:
  - name: QQ
    link: tencent://message/?uin=1581893646&Site=Sambow&Menu=yes
    icon: ri:qq-line
    color: '#12B7F5'
  - name: GitHub
    link: https://github.com/HanaNoryu
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:HanaNoryu@outlook.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=391356695
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: 哔哩哔哩动画
    link: https://space.bilibili.com/10273650
    icon: ri:bilibili-line
    color: '#FF8EB3'

banner:
  enable: true
  title:
    - Noryu
    - の
    - 杂
    - 物
    - 铺
  border: false
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
notice:
  enable: true
  content: いつか想いが叶うまで

bg_image:
  enable: true
  url: https://s2.loli.net/2022/11/02/BqxzoClAmNYUDs2.jpg # recomend image related to your mode
  dark: https://cdn.yunyoujun.cn/img/bg/galaxy.jpg
  # blur: 30px
  opacity: 0.8

search:
  modal: true
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  dark_bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg

fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

medium_zoom: true

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: 你猜
  custom:
    title: 关于站点
    path: /about/site
    icon: ri:settings-line

pages:
  - name: 我的小伙伴们
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

post_card:
  opacity: 0.8

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: 很遗憾，咱没写啥目录
  collapse: false

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

reward:
  enable: false
  icon: ri:hand-coin-line
  comment: I'm so cute. Please give me money.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: 支付宝
      path: https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
      # link: https://xxxx
    - name: QQ 支付
      path: https://cdn.yunyoujun.cn/img/donate/qqpay-qrcode.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: 微信支付
      path: https://cdn.yunyoujun.cn/img/donate/wechatpay-qrcode.jpg
      color: '#2DC100'
      icon: ri:wechat-pay-line

footer:
  since: 2022
  icon:
    name: ri:cloud-line
    animated: true
    color: '#0078E7'
    url:
    title:
  powered:
    enable: true
  beian:
    enable: true
    icp: 豫ICP备2022025836号
    # 公安备案
    gongan:
      enable: false
      text: 京公网安备 XXXXXXXX 号
      id: XXXXXXXX
  live_time:
    enable: false
    prefix: 本博客已萌萌哒地运行
    suffix: (●'◡'●)
    start_time: '2019-04-12T00:00:00'
  support:
    enable: true
    title: 又拍云
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://image.hananoryu.cn/images/upyun_logo.png
    prefix: 本网站由
    suffix: 提供 CDN 加速

say:
  enable: false
  api:
  # https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

wordcloud:
  enable: true
  height: 350

wordcount:
  enable: true
  count: true
  time: true

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname:
  apikey:

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo:
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

engine_search:
  enable: false

algolia_search:
  enable: true
  hits:
    per_page: 10 # the number of search results per page

baidu_push: true

google_analytics:
  enable: true
  id: G-G7ZRGQGP5K

google_adsense:
  enable: false
  client:
