mode: auto

avatar:
  url: https://s2.loli.net/2022/10/31/JNEaybrIPDfVtqH.png
  rounded: true
  opacity: 1

social:
  - name: GitHub
    link: https://github.com/HanaNoryu
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:HanaNoryu@outlook.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=391356695
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: 哔哩哔哩动画
    link: https://space.bilibili.com/10273650
    icon: ri:bilibili-line
    color: '#FF8EB3'

banner:
  enable: true
  title:
    - Noryu
    - の
    - 杂
    - 物
    - 铺
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
# notice:
#   enable: true
#   content: Thanks for playing my game.

bg_image:
  enable: true
  url: /images/homepage.jpg
  # dark:
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8

search:
  modal: true
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  dark_bg_image: xxx

fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

medium_zoom: true

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: 你猜
  custom:
    title: 留言板
    path: /about/#comment
    icon: ri:settings-line

pages:
  - name: 我的小伙伴们
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

post_card:
  opacity: 0.8

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: 很遗憾，咱没写啥目录
  collapse: false

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true

lazyload:
  enable: true

footer:
  since: 2022
  powered:
    enable: true
  beian:
    enable: true
    icp: 苏ICP备xxxxxxxx号
    # 公安备案
    gongan:
      enable: false
      text: 京公网安备 XXXXXXXX 号
      id: XXXXXXXX
  live_time:
    enable: false
    prefix: 本博客已萌萌哒地运行
    suffix: (●'◡'●)
    start_time: '2019-04-12T00:00:00'
  support:
    enable: true
    title: 又拍云
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: 本网站由
    suffix: 提供 CDN 加速
  say:
    enable: true
    api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
    # https://developer.hitokoto.cn/sentence/
    hitokoto:
      enable: true
      api: https://v1.hitokoto.cn

wordcloud:
  enable: true

wordcount:
  enable: true
  count: true
  time: true
